# Generated by Django 4.2.15 on 2024-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_failedprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('PAN', 'Pending-Annotation'), ('PRV', 'Pending-Review'), ('APR', 'Approved'), ('REJ', 'Rejected')], default='PAN', max_length=3),
        ),
    ]
