# Generated by Django 4.2.15 on 2024-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20231103_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('ANT', 'Annotating'), ('RVW', 'Reviewing'), ('RVD', 'Reviewed'), ('CMP', 'Completed'), ('SCR', 'Scraped')], default='ANT', max_length=3),
        ),
    ]
