# Generated by Django 4.2.15 on 2024-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_project_assigned_annotator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('ANT', 'Annotating'), ('RVW', 'Reviewing'), ('RVD', 'Reviewed'), ('CMP', 'Completed'), ('SCR', 'Scraped')], default='ANT', max_length=10),
        ),
    ]
